#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit

echo ''
echo "********************************* JAVA VERSION *********************************"
/usr/lib/jvm/java-1.8.0/bin/java -version
echo "********************************************************************************"
echo ''

export JAVA_HOME=/usr/lib/jvm/java-1.8.0/bin/java
export JDK_HOME=/usr/lib/jvm/java-1.8.0/bin/java

cat /dev/null | /usr/lib/jvm/java-1.8.0/bin/java -Xmx4096M \
  -XX:ReservedCodeCacheSize=128m \
  -Dsbt.log.noformat=true \
  -XX:+UseConcMarkSweepGC \
  -jar `dirname $0`/sbt-launch.jar "$@"
